databases:
  - name: my_budget_app
    databaseName: my_budget_app_6kfz
    user: my_budget_app_6kfz_user
services:
  - type: web
    name: budget_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_budget_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false